const { withXcodeProject, withInfoPlist, withDangerousMod } = require("expo/config-plugins");
const fs = require("fs");
const path = require("path");

// Keep in sync with the hand-authored ios/OBHInvites/SceneDelegate.swift
// this plugin re-generates on every prebuild — `expo prebuild` regenerates
// `ios/` from scratch (it's gitignored), so anything not declared here or
// in app.json is silently lost the next time someone runs it.
const MAIN_TARGET_NAME = "OBHInvites";
const SCENE_DELEGATE_FILENAME = "SceneDelegate.swift";

const SCENE_DELEGATE_SOURCE = [
  "import UIKit",
  "import React",
  "",
  "// Standard UIScene lifecycle entry point — required because iOS 27 hard-",
  "// crashes any app that never adopts scenes at all (EXC_BREAKPOINT in",
  "// UIKit's _UIApplicationEvaluateRuntimeIssueForNoSceneLifecycleAdoption;",
  "// older OSes only logged a runtime-issue warning). Expo's ExpoAppDelegate",
  "// (SDK 54 / RN 0.81) has no scene-lifecycle support built in yet, so this",
  "// is hand-rolled.",
  "//",
  "// It does NOT create its own window or call factory.startReactNative",
  "// again — AppDelegate already does both synchronously in",
  "// didFinishLaunchingWithOptions (expo-dev-launcher's own AppDelegate",
  "// subscriber requires `window` to exist by then, before any scene has",
  "// connected). This just attaches that existing window to the scene, plus",
  "// handles the URL/user-activity events AppDelegate's own",
  "// application(_:open:) / application(_:continue:) stop receiving once",
  "// a scene is registered — without this, deep links and the",
  "// invites.falcon83.com universal links would silently stop working for",
  "// an already-running app.",
  "//",
  "// Generated by plugins/withSceneDelegate.js on every prebuild — edit",
  "// that file, not this one; expo prebuild overwrites this file from it.",
  "class SceneDelegate: UIResponder, UIWindowSceneDelegate {",
  "  var window: UIWindow?",
  "",
  "  func scene(",
  "    _ scene: UIScene,",
  "    willConnectTo session: UISceneSession,",
  "    options connectionOptions: UIScene.ConnectionOptions",
  "  ) {",
  "    guard let windowScene = scene as? UIWindowScene else { return }",
  "",
  "    if let appDelegate = UIApplication.shared.delegate as? AppDelegate, let window = appDelegate.window {",
  "      window.windowScene = windowScene",
  "      self.window = window",
  "    } else {",
  "      // Shouldn't happen — AppDelegate creates `window` synchronously",
  "      // before any scene connects — but fall back rather than leave the",
  "      // scene windowless.",
  "      self.window = UIWindow(windowScene: windowScene)",
  "    }",
  "",
  "    // Cold launch via a link/universal link — the app-level equivalents",
  "    // (application(_:open:), application(_:continue:)) don't fire for a",
  "    // scene-based app, so handle it here instead.",
  "    if let url = connectionOptions.urlContexts.first?.url {",
  "      RCTLinkingManager.application(UIApplication.shared, open: url, options: [:])",
  "    } else if let userActivity = connectionOptions.userActivities.first {",
  "      RCTLinkingManager.application(UIApplication.shared, continue: userActivity) { _ in }",
  "    }",
  "  }",
  "",
  "  // Warm launch: link tapped / URL scheme opened while the app is already running.",
  "  func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {",
  "    guard let url = URLContexts.first?.url else { return }",
  "    RCTLinkingManager.application(UIApplication.shared, open: url, options: [:])",
  "  }",
  "",
  "  // Warm launch: universal link / Handoff continuation while already running.",
  "  func scene(_ scene: UIScene, continue userActivity: NSUserActivity) {",
  "    RCTLinkingManager.application(UIApplication.shared, continue: userActivity) { _ in }",
  "  }",
  "}",
  "",
].join("\n");

/** Writes SceneDelegate.swift into ios/OBHInvites/ on every prebuild. */
function withSceneDelegateSource(config) {
  return withDangerousMod(config, [
    "ios",
    (cfg) => {
      const targetDir = path.join(cfg.modRequest.platformProjectRoot, MAIN_TARGET_NAME);
      fs.mkdirSync(targetDir, { recursive: true });
      fs.writeFileSync(path.join(targetDir, SCENE_DELEGATE_FILENAME), SCENE_DELEGATE_SOURCE);
      return cfg;
    },
  ]);
}

/** Registers SceneDelegate.swift in the Xcode project + main target's Sources build phase. */
function withSceneDelegateXcodeProject(config) {
  return withXcodeProject(config, (cfg) => {
    const project = cfg.modResults;
    const filePath = `${MAIN_TARGET_NAME}/${SCENE_DELEGATE_FILENAME}`;

    // Idempotent — prebuild (without --clean) can run against an ios/
    // folder that already has this from a previous run.
    if (project.hasFile(filePath)) return cfg;

    const groupKey = project.findPBXGroupKey({ name: MAIN_TARGET_NAME });
    const targetUuid = project.findTargetKey(MAIN_TARGET_NAME);
    if (!groupKey || !targetUuid) {
      throw new Error(
        `withSceneDelegate: couldn't find the "${MAIN_TARGET_NAME}" group/target in the Xcode project — ` +
          "check MAIN_TARGET_NAME in plugins/withSceneDelegate.js still matches the Xcode project."
      );
    }
    project.addSourceFile(filePath, { target: targetUuid }, groupKey);
    return cfg;
  });
}

/**
 * Declares UIScene support — required since iOS 27 hard-crashes any app
 * that never adopts it at all (EXC_BREAKPOINT in UIKit's
 * _UIApplicationEvaluateRuntimeIssueForNoSceneLifecycleAdoption). Older
 * OSes only logged a runtime-issue warning about it.
 */
function withSceneManifest(config) {
  return withInfoPlist(config, (cfg) => {
    cfg.modResults.UIApplicationSceneManifest = {
      UIApplicationSupportsMultipleScenes: false,
      UISceneConfigurations: {
        UIWindowSceneSessionRoleApplication: [
          {
            UISceneConfigurationName: "Default Configuration",
            UISceneDelegateClassName: "$(PRODUCT_MODULE_NAME).SceneDelegate",
          },
        ],
      },
    };
    return cfg;
  });
}

module.exports = function withSceneDelegate(config) {
  config = withSceneDelegateSource(config);
  config = withSceneDelegateXcodeProject(config);
  config = withSceneManifest(config);
  return config;
};
